name: xsd
description: A XML Schema Datatypes Interop Library for Dart
version: 0.1.0-dev
repository: https://github.com/dropbear-software/xsd
issue_tracker: https://github.com/dropbear-software/xsd/issues
topics:
  - xsd
  - xml
  - xml_schema
  - interop
  - datatypes

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.2
  decimal: ^3.2.4
  intl: ^0.20.2
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
